// Code generated by "stringer -type Type -linecomment"; DO NOT EDIT.

package token

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Illegal-0]
	_ = x[EOF-1]
	_ = x[Newline-2]
	_ = x[Whitespace-3]
	_ = x[Ident-4]
	_ = x[Tag-5]
	_ = x[Var-6]
	_ = x[String-7]
	_ = x[Int-8]
	_ = x[Float-9]
	_ = x[Other-10]
	_ = x[symbolStart-11]
	_ = x[OpenDoc-12]
	_ = x[CloseDoc-13]
	_ = x[Asterisk-14]
	_ = x[Backslash-15]
	_ = x[Qmark-16]
	_ = x[Lparen-17]
	_ = x[Rparen-18]
	_ = x[Lbrack-19]
	_ = x[Rbrack-20]
	_ = x[Lbrace-21]
	_ = x[Rbrace-22]
	_ = x[Lt-23]
	_ = x[Gt-24]
	_ = x[Comma-25]
	_ = x[Colon-26]
	_ = x[DoubleColon-27]
	_ = x[Ellipsis-28]
	_ = x[Or-29]
	_ = x[And-30]
	_ = x[Assign-31]
	_ = x[symbolEnd-32]
	_ = x[keywordStart-33]
	_ = x[This-34]
	_ = x[Array-35]
	_ = x[Object-36]
	_ = x[Callable-37]
	_ = x[Static-38]
	_ = x[keywordEnd-39]
}

const _Type_name = "IllegalEOF\\nWhitespaceIdentTagVarStringIntFloatOthersymbolStart/***/*\\?()[]{}<>,:::...|&=symbolEndkeywordStart$thisarrayobjectcallablestatickeywordEnd"

var _Type_index = [...]uint8{0, 7, 10, 12, 22, 27, 30, 33, 39, 42, 47, 52, 63, 66, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 83, 86, 87, 88, 89, 98, 110, 115, 120, 126, 134, 140, 150}

func (i Type) String() string {
	if i >= Type(len(_Type_index)-1) {
		return "Type(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Type_name[_Type_index[i]:_Type_index[i+1]]
}
